version: "3"
services:
  timescaledb:
    # image: timescale/timescaledb:1.7.0-pg12
    image: postgres:12.4-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=Welcome
      - POSTGRES_DB=zabbix
    volumes:
      # - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/sqls:/docker-entrypoint-initdb.d

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-5.0-latest
    ports:  
      - '10051:10051'
    environment:
      - DB_SERVER_HOST=timescaledb
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=Welcome
    depends_on:
      - timescaledb

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    ports:
      - '8080:8080'
    depends_on:
      - timescaledb
    environment: 
      - DB_SERVER_HOST=timescaledb
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=Welcome
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Lisbon

