version: "3"
services:
  timescaledb:
    image: timescale/timescaledb:1.7.0-pg12
    # image: postgres:12.4-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=Welcome
      - POSTGRES_DB=zabbix
    volumes:
      - ./db/data:/var/lib/postgresql/data
      # - ./postgresql/sqls:/docker-entrypoint-initdb.d

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-5.0-latest
    ports:  
      - "10051:10051"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - DB_SERVER_HOST=timescaledb
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=Welcome
    depends_on:
      - timescaledb

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-5.0-latest
    ports:
      # - '8080:8080'
      - '443:8443'
    depends_on:
      - timescaledb
    volumes:
      - /etc/letsencrypt/live/zabbix-test.duckdns.org/fullchain.pem:/etc/ssl/nginx/ssl.crt
      - /etc/letsencrypt/live/zabbix-test.duckdns.org/privkey.pem:/etc/ssl/nginx/ssl.key
      - ./certificates/dhparam.pem:/etc/ssl/nginx/dhparam.pem
    environment: 
      - DB_SERVER_HOST=timescaledb
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=Welcome
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Lisbon

