version: "2"

services:
  grafana:
    image: grafana/grafana:7.3.2
    ports:
      - 3000:3000
    user: "104"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./grafana/plugins/:/var/lib/grafana/plugins/
    restart: unless-stopped
volumes:
  grafana_data: {}
